### ISSUE TITLE
Security updates needed

### ISSUE THREAD

**Issue by mogul** [ajilach/clamav-rest#15]
Various vulnerable versions of libclamav and Go libraries are in use, and the vulnerabilities are rated "High". I don't want to report the details here, but you can see them easily by logging into https://slim.ai, searching for `ajilaag/clamav-rest`, and clicking on `Vulnerabilities`. There you'll see the details in the `Vulnerabilities` and `Packages` sub-tabs. There are 3 and 8 entries on each tab respectively.

**Comment by rhermanek** [comment]
Hey mogul
I could indeed see that some vulnerabilities are there and confirmed it using docker scan and snyk.
I have since changed the build-image to golang:alpine and according to snyk there are no more vulnerable paths. However, slim.ai still finds some vulnerabilities which I don't think apply here.

**Comment by mogul** [comment]
Great, thanks for the quick response!
